# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvSqAj1esL4PD16DRWHAWtbCyF3Sz4hw
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('data.csv')

import random

N = 10000
d = 10

ads = []

reward1 = [0] * d
reward0 = [0] * d
total_reward = 0

for n in range(N):
  ad = 0
  max_random = 0

  for i in range(d):
    random_beta = random.betavariate(reward1[i] + 1, reward0[i] + 1)
    if random_beta > max_random:
      max_random = random_beta
      ad = i

  ads.append(ad)
  reward = dataset.values[n, ad]

  if reward == 1:
    reward1[ad] += 1
  else:
    reward0[ad] += 1

  total_reward += reward

plt.hist(ads)
plt.show()