# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvSqAj1esL4PD16DRWHAWtbCyF3Sz4hw
"""

from google.colab import files
data = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

X = df.iloc[:, 1: -1].values
y = df.iloc[:, -1].values

y = y.reshape(len(y), 1)

from sklearn.preprocessing import StandardScaler

sc1 = StandardScaler()
sc2 = StandardScaler()

X = sc1.fit_transform(X)
y = sc2.fit_transform(y)

from sklearn.svm import SVR

regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

sc2.inverse_transform(regressor.predict(sc1.transform([[6.5]])).reshape(-1, 1))

plt.scatter(sc1.inverse_transform(X), sc2.inverse_transform(y), color = 'red')
plt.plot(sc1.inverse_transform(X), sc2.inverse_transform(regressor.predict(X).reshape(-1, 1)), color = 'blue')
plt.show()

#For smoother curve
X_grid = np.arange(min(sc1.inverse_transform(X)), max(sc1.inverse_transform(X)), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc1.inverse_transform(X), sc2.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc2.inverse_transform(regressor.predict(sc1.transform(X_grid)).reshape(-1,1)), color = 'blue')
plt.show()

# For learning about kernels
# https://data-flair.training/blogs/svm-kernel-functions/