# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvSqAj1esL4PD16DRWHAWtbCyF3Sz4hw
"""

from google.colab import files
data = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('data_poly.csv')

X = df.iloc[:, 1: -1].values
y = df.iloc[:, -1].values

from sklearn.linear_model import LinearRegression

lin = LinearRegression()
lin.fit(X, y)

from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 4)
X_poly = poly.fit_transform(X)
lin2 = LinearRegression()
lin2.fit(X_poly, y)

plt.scatter(X, y, color = 'red')
plt.plot(X, lin.predict(X), color = 'blue')
plt.title("Linear Regression Results")
plt.show()

plt.scatter(X, y, color = 'red')
plt.plot(X, lin2.predict(X_poly), color = 'blue')
plt.title("Polynomial Regression Results")
plt.show()

print(lin.predict([[6.5]]))

print(lin2.predict(poly.fit_transform([[6.5]])))