# -*- coding: utf-8 -*-
"""practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rvSqAj1esL4PD16DRWHAWtbCyF3Sz4hw
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, [3, 4]].values

from sklearn.cluster import KMeans
wcss = []

for i in range(1, 11):
  kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss)
plt.show()

kmeans = KMeans(n_clusters = 5, init = 'k-means++', random_state = 42)
y = kmeans.fit_predict(X)
print(y)

plt.scatter(X[y == 0, 0], X[y == 0, 1], s = 100, label = 'Cluster 1', c = "blue")
plt.scatter(X[y == 1, 0], X[y == 1, 1], s = 100, label = 'Cluster 2', c = "red")
plt.scatter(X[y == 2, 0], X[y == 2, 1], s = 100, label = 'Cluster 3', c = "green")
plt.scatter(X[y == 3, 0], X[y == 3, 1], s = 100, label = 'Cluster 4', c = "magenta")
plt.scatter(X[y == 4, 0], X[y == 4, 1], s = 100, label = 'Cluster 5', c = "cyan")

plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = "yellow", label = "centroids")
plt.show()